import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GROUPS = ["cooperative", "fleet", "coldchain"] as const;
const PKG_ROOT = path.resolve(__dirname, "..");
const MIGRATIONS_ROOT = path.resolve(PKG_ROOT, "migrations");

let outputCode = `// ⚠️ Auto-generated by scripts/bundle-migrations.ts. Do not edit directly.\n\n`;

for (const group of GROUPS) {
    const dir = path.join(MIGRATIONS_ROOT, group);
    let files: string[] = [];

    if (fs.existsSync(dir)) {
        files = fs.readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
    }

    const migrationContents = files.map((file) => {
        const rawSql = fs.readFileSync(path.join(dir, file), "utf-8");
        return {
            name: file,
            sql: rawSql.trim(),
        };
    });

    outputCode += `export const ${group}Migrations = ${JSON.stringify(migrationContents, null, 2)};\n\n`
}

fs.writeFileSync(path.resolve(PKG_ROOT, 'src/migrations-registry.ts'), outputCode);
console.log('✅ Migration registry successfully bundled into memory.');