import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GROUPS = ["cooperative", "fleet", "coldchain"] as const;
const PKG_ROOT = path.resolve(__dirname, "..");
const MIGRATIONS_ROOT = path.resolve(PKG_ROOT, "migrations");

let outputCode = `// ⚠️ Auto-generated by scripts/bundle-migrations.ts. Do not edit directly.\n\n`;

console.log(PKG_ROOT, MIGRATIONS_ROOT);
for (const group of GROUPS) {
    const dir = path.join(MIGRATIONS_ROOT, group);
    let migrationContents: Array<{ name: string, sql: string }> = [];

    if (fs.existsSync(dir)) {
        const timestampFolders = fs.readdirSync(dir)
            .filter((f) => fs.statSync(path.join(dir, f)).isDirectory() && f !== 'meta')
            .sort();
        // files = fs.readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
        for (const timestampFolder of timestampFolders) {
            const sqlFilePath = path.join(dir, timestampFolder, "migration.sql");
            if (fs.existsSync(sqlFilePath)) {
                const rawSql = fs.readFileSync(sqlFilePath, "utf-8");
                migrationContents.push({
                    name: `${timestampFolder}/migration.sql`,
                    sql: rawSql.trim()
                });
            }
        }
    } else {
        console.warn(`⚠️ Warning: Directory not found for ${group} at ${dir}`);
    }

    // const migrationContents = files.map((file) => {
    //     const rawSql = fs.readFileSync(path.join(dir, file), "utf-8");
    //     return {
    //         name: file,
    //         sql: rawSql.trim(),
    //     };
    // });

    outputCode += `export const ${group}Migrations = ${JSON.stringify(migrationContents, null, 2)};\n\n`
}

fs.writeFileSync(path.resolve(PKG_ROOT, 'src/migrations-registry.ts'), outputCode);
console.log('✅ Migration registry successfully bundled into memory.');