// ⚠️ Auto-generated by scripts/bundle-migrations.ts. Do not edit directly.

export const cooperativeMigrations = [
  {
    "name": "20261006233846_useful_shotgun/migration.sql",
    "sql": "CREATE TABLE `farmers` (\n\t`id` text PRIMARY KEY,\n\t`full_name` text NOT NULL,\n\t`phone_number` text NOT NULL UNIQUE,\n\t`location_hub` text NOT NULL,\n\t`farm_size_acres` real NOT NULL,\n\t`crop_variety` text NOT NULL,\n\t`created_at` integer DEFAULT 1791329926\n);"
  }
];

export const fleetMigrations = [];

export const coldchainMigrations = [];

